name: my_app7
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^1.3.0
  url_launcher: ^6.3.1
  geolocator: ^14.0.0
  flutter_svg: ^2.1.0 
  material_design_icons_flutter: ^7.0.7296
  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  intl: ^0.20.2
  camera: ^0.11.1
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  build_runner: ^2.4.15
  flutter_lints: ^5.0.0

flutter:
  assets:
    - assets/weather.png
    - assets/calculate.png
    - assets/person.png
    - assets/search.png
    - assets/wind.png
    - assets/back.png
uses-material-design: true 
